// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChoiuqm9ivLcrXEzKhzkRiGaBX04LJsgE',
    appId: '1:1081623550709:web:afc55aef2908da508883bc',
    messagingSenderId: '1081623550709',
    projectId: 'projektinz-274ba',
    authDomain: 'projektinz-274ba.firebaseapp.com',
    storageBucket: 'projektinz-274ba.firebasestorage.app',
    measurementId: 'G-V4M9MPRL33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-cnhpMBG-RbfCWjsWlr5IIMSVXCq0K0A',
    appId: '1:1081623550709:android:eb5bd8e802f2cc508883bc',
    messagingSenderId: '1081623550709',
    projectId: 'projektinz-274ba',
    storageBucket: 'projektinz-274ba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUAZAlWIUsmmTLK7hP17uv_cZE7IXQBxg',
    appId: '1:1081623550709:ios:800163f9657330098883bc',
    messagingSenderId: '1081623550709',
    projectId: 'projektinz-274ba',
    storageBucket: 'projektinz-274ba.firebasestorage.app',
    androidClientId: '1081623550709-21r5fk0hdqd446r03bf6tboajpj7nfa2.apps.googleusercontent.com',
    iosClientId: '1081623550709-fmbc1uno42bnt0am7d13eqommilgo0e0.apps.googleusercontent.com',
    iosBundleId: 'com.example.projekt',
  );

}